### PR TITLE
upgrade h2 test dependency due to cves

### PR DESCRIPTION
**Pull request by pjfanning**
https://mvnrepository.com/artifact/com.h2database/h2/1.4.200 - 4 CVEs

### CODE REVIEW

**Comment by nvollmar** [comment]
There were some significant changes in H2 2.0: https://www.h2database.com/html/migration-to-v2.html

**Comment by nvollmar** [comment]
@pjfanning You need to update `CHAR` to `VARCHAR` in the statement in `org.apache.pekko.projection.jdbc.JdbcProjectionSpec` (line 186):
```
       create table if not exists "$table" (
        "ID" VARCHAR(255) NOT NULL,
        "CONCATENATED" VARCHAR(255) NOT NULL
       );
```

That will fix the test

**Review by nvollmar — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
@nvollmar thanks for the suggestion about the test code SQL

**Pull request merged**
